import { chromium } from '@playwright/test';
import { readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
const image = `data:image/jpeg;base64,${(await readFile('public/assets/olive-hills.jpg')).toString('base64')}`;
const chrome = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const browser = await chromium.launch(existsSync(chrome) ? { executablePath: chrome } : {});
const page = await browser.newPage({ viewport: { width: 1080, height: 1350 }, deviceScaleFactor: 1 });
await page.setContent(`<!doctype html><html><head><style>
*{box-sizing:border-box}body{margin:0;background:#fcfaf3;color:#2d352b}img{display:block;width:100%;height:425px;object-fit:cover;object-position:50% 68%}.body{height:925px;padding:64px 90px 48px;display:flex;flex-direction:column;text-align:center;align-items:center}.eyebrow{font:17px/1.4 Arial,sans-serif;letter-spacing:4px;color:#596151;margin:0 0 44px}blockquote{font:64px/1.38 Georgia,serif;letter-spacing:-1.3px;margin:0;flex:1;display:flex;align-items:center}.reference{font:20px/1.5 Arial,sans-serif;letter-spacing:4px;margin:38px 0 12px;color:#475b37}.translation{font:12px/1.5 Arial,sans-serif;letter-spacing:3px;color:#596151;margin:0}.rule{width:58px;height:1px;background:#a1ae92;margin:37px 0 27px}.brand{font:27px/1 Georgia,serif;margin:0}.url{font:12px/1.5 Arial,sans-serif;letter-spacing:2px;color:#596151;margin:12px 0 0}
</style></head><body><img src="${image}" alt=""><div class="body"><p class="eyebrow">AN INVITATION TO REST</p><blockquote>“Come to me, all you who labor and are heavily burdened, and I will give you rest.”</blockquote><p class="reference">MATTHEW 11:28</p><p class="translation">WORLD ENGLISH BIBLE</p><span class="rule"></span><p class="brand">MaxDay</p><p class="url">GETMAXDAY.COM</p></div></body></html>`);
await page.locator('img').evaluate(img => img.decode());
await page.screenshot({ path: 'public/assets/matthew-11-28-card.png' });
await page.setViewportSize({ width: 1200, height: 630 });
await page.setContent(`<!doctype html><html><head><style>*{box-sizing:border-box}body{margin:0;background:#f7f5ee;color:#2d352b;display:flex;width:1200px;height:630px}.copy{width:550px;padding:65px 54px;display:flex;flex-direction:column}.brand{font:30px Georgia,serif;margin:0 0 53px}.eyebrow{font:12px Arial,sans-serif;letter-spacing:3px;color:#475b37;margin:0 0 23px}h1{font:67px/1.13 Georgia,serif;letter-spacing:-2px;margin:0}em{color:#475b37}p{font:22px/1.6 Arial,sans-serif;color:#596151;margin:26px 0 0}.url{font:12px Arial,sans-serif;letter-spacing:2px;margin-top:auto}img{width:650px;height:630px;object-fit:cover;object-position:60% 70%}</style></head><body><div class="copy"><div class="brand">MaxDay</div><div class="eyebrow">SCRIPTURE &amp; PRAYER</div><h1>Find a moment<br>of <em>peace.</em></h1><p>A Bible verse and prayer,<br>with a free card to keep.</p><div class="url">GETMAXDAY.COM</div></div><img src="${image}" alt=""></body></html>`);
await page.locator('img').evaluate(img => img.decode());
await page.screenshot({ path: 'public/assets/social-preview.jpg', type: 'jpeg', quality: 86 });
await browser.close();
await writeFile('public/assets/matthew-11-28-print.html', `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex, nofollow"><title>Print your Scripture card · MaxDay</title><link rel="icon" href="favicon.svg" type="image/svg+xml"><style>*{box-sizing:border-box}body{margin:0;padding:25px;background:#f7f5ee;color:#2d352b;text-align:center;font:16px/1.6 -apple-system,BlinkMacSystemFont,'Segoe UI',Arial,sans-serif}.controls{margin:0 auto 25px;max-width:460px}.controls p{margin:10px 0 15px}button{background:#475b37;color:#fff;border:0;border-radius:4px;padding:13px 26px;font:inherit;cursor:pointer}a{color:inherit;margin-left:20px;text-underline-offset:4px}button:focus-visible,a:focus-visible{outline:3px solid #856634;outline-offset:4px}img{display:block;width:min(100%,432px);height:auto;margin:auto;border:1px solid #d9ddcf}@page{margin:15mm}@media print{body{background:white;padding:0}.controls{display:none}img{width:125mm;max-width:100%;border:0;break-inside:avoid}}</style></head><body><div class="controls"><p>Your Scripture card is ready to print.</p><button type="button" onclick="window.print()">Print this card</button><a href="../">Back to the reflection</a><noscript><p>Choose Print from your browser’s menu.</p></noscript></div><img src="matthew-11-28-card.png" width="1080" height="1350" alt="Come to me, all you who labor and are heavily burdened, and I will give you rest. Matthew 11:28, World English Bible. MaxDay."></body></html>`);
console.log('Generated the Scripture card, social preview, and printable page.');
